version: "3.7"
services:
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./repos:/var/www/git
  go-service:
    build:
      dockerfile: goservice.Dockerfile
      context: .
    ports: 
      - "3000:60"
    volumes:
      - ./repos:/app
    restart: always
    stdin_open: true
    tty: true
